import os
import json
import datetime
import numpy as np 
import pandas as pd # Only needed if we integrate parts of feature extraction later
from collections import defaultdict
import math
import time
import random

# --- Configuration ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "generated_logs_2") # Save to the same dir
NUM_LOGS_TO_GENERATE = 500
BASE_LABEL = "normal_detailed" # Label for all logs generated by this script

# --- Question Data ---
# (Ensure this is the same as used in other scripts)
questions_data = [
    # Maths
    {"id": "q1", "subject": "Maths", "difficulty": "Easy", "text": "If x^2 - 5x + 6 = 0, find x.", "options": ["1 and 6", "2 and 3", "3 and 4", "None"], "correct_answer": 1},
    {"id": "q2", "subject": "Maths", "difficulty": "Easy", "text": "Derivative of sin(x)?", "options": ["cos(x)", "-cos(x)", "-sin(x)", "sin(x)"], "correct_answer": 0},
    {"id": "q3", "subject": "Maths", "difficulty": "Easy", "text": "Distance between (1,2) and (4,6)?", "options": ["5", "4", "3", "2"], "correct_answer": 0},
    {"id": "q4", "subject": "Maths", "difficulty": "Medium", "text": "If det(A) = 5, what is det(2A)?", "options": ["10", "20", "25", "40"], "correct_answer": 1},
    {"id": "q5", "subject": "Maths", "difficulty": "Medium", "text": "Evaluate ∫x^2 dx.", "options": ["x^2/2", "x^3/3", "x^3", "x^2"], "correct_answer": 1},
    {"id": "q6", "subject": "Maths", "difficulty": "Medium", "text": "If z = 1+i, find |z|.", "options": ["1", "√2", "2", "√3"], "correct_answer": 1},
    {"id": "q7", "subject": "Maths", "difficulty": "Medium", "text": "Find equation of line: slope 2 through (1,3).", "options": ["y=2x+1", "y-3=2(x-1)", "y=x+2", "y=2x-3"], "correct_answer": 1},
    {"id": "q8", "subject": "Maths", "difficulty": "Hard", "text": "Solve sin(2x)=√3/2.", "options": ["x=30°,150°", "x=45°", "x=60°", "None"], "correct_answer": 0},
    {"id": "q9", "subject": "Maths", "difficulty": "Hard", "text": "Solve log(x^2-5x+6)=0.", "options": ["x=2,3", "x=1,6", "x=3,4", "x=1,2"], "correct_answer": 0},
    {"id": "q10", "subject": "Maths", "difficulty": "Hard", "text": "Area between y=x^2 and y=x (0 to 1)?", "options": ["1/6", "1/3", "1/2", "1"], "correct_answer": 0},
    {"id": "q11", "subject": "Physics", "difficulty": "Easy", "text": "Unit of Force?", "options": ["Joule", "Newton", "Pascal", "Watt"], "correct_answer": 1},
    {"id": "q12", "subject": "Physics", "difficulty": "Easy", "text": "g on Earth?", "options": ["8.9", "9.8", "10.2", "9"], "correct_answer": 1},
    {"id": "q13", "subject": "Physics", "difficulty": "Easy", "text": "Resistance if V=10V, I=2A?", "options": ["20Ω", "5Ω", "2Ω", "10Ω"], "correct_answer": 1},
    {"id": "q14", "subject": "Physics", "difficulty": "Medium", "text": "Law of electromagnetic induction?", "options": ["Lenz", "Newton", "Ohm", "Ampere"], "correct_answer": 0},
    {"id": "q15", "subject": "Physics", "difficulty": "Medium", "text": "Speed of light?", "options": ["3x10^8", "3x10^6", "3x10^5", "Both A & C"], "correct_answer": 0},
    {"id": "q16", "subject": "Physics", "difficulty": "Medium", "text": "Time to fall 20m (g=10)?", "options": ["2s", "3s", "4s", "2s"], "correct_answer": 0},
    {"id": "q17", "subject": "Physics", "difficulty": "Medium", "text": "Electric field at r from q?", "options": ["q/4πε₀r", "q/4πε₀r²", "q/r", "q/r²"], "correct_answer": 1},
    {"id": "q18", "subject": "Physics", "difficulty": "Hard", "text": "Block on incline θ=30°, L=5m, time?", "options": ["1s", "2s", "3s", "4s"], "correct_answer": 1},
    {"id": "q19", "subject": "Physics", "difficulty": "Hard", "text": "Freq LC circuit L=1H, C=1μF?", "options": ["50Hz", "5kHz", "159Hz", "159kHz"], "correct_answer": 3},
    {"id": "q20", "subject": "Physics", "difficulty": "Hard", "text": "Photon energy of 500nm light?", "options": ["3.98eV", "2.48eV", "1.24eV", "4.13eV"], "correct_answer": 1},
    {"id": "q21", "subject": "Chemistry", "difficulty": "Easy", "text": "Atomic number of Oxygen?", "options": ["6", "7", "8", "9"], "correct_answer": 2},
    {"id": "q22", "subject": "Chemistry", "difficulty": "Easy", "text": "Valency of Nitrogen?", "options": ["2", "3", "4", "5"], "correct_answer": 1},
    {"id": "q23", "subject": "Chemistry", "difficulty": "Easy", "text": "Hybridization in CH₄?", "options": ["sp", "sp²", "sp³", "dsp²"], "correct_answer": 2},
    {"id": "q24", "subject": "Chemistry", "difficulty": "Medium", "text": "Oxidizer in Zn + CuSO₄?", "options": ["Zn", "CuSO₄", "Cu", "ZnSO₄"], "correct_answer": 1},
    {"id": "q25", "subject": "Chemistry", "difficulty": "Medium", "text": "Identify nucleophile?", "options": ["NH₃", "H₂O", "NO₃⁻", "SO₄²⁻"], "correct_answer": 0},
    {"id": "q26", "subject": "Chemistry", "difficulty": "Medium", "text": "Moles in 22.4L at STP?", "options": ["1", "2", "0.5", "1.5"], "correct_answer": 0},
    {"id": "q27", "subject": "Chemistry", "difficulty": "Medium", "text": "pH of 0.01M HCl?", "options": ["1", "2", "3", "4"], "correct_answer": 0},
    {"id": "q28", "subject": "Chemistry", "difficulty": "Hard", "text": "ΔH with given bond energies?", "options": ["-184kJ", "-117kJ", "+184kJ", "+117kJ"], "correct_answer": 0},
    {"id": "q29", "subject": "Chemistry", "difficulty": "Hard", "text": "Lattice energy order?", "options": ["NaCl", "KCl", "RbCl", "CsCl"], "correct_answer": 0},
    {"id": "q30", "subject": "Chemistry", "difficulty": "Hard", "text": "Rate law (2nd order)?", "options": ["k[A]", "k[A]^2", "k[B]", "k[A][B]"], "correct_answer": 1},
]
question_details_lookup = {q["id"]: q for q in questions_data}
TIME_LIMIT_SECONDS = 60 * 60 # 60 minutes
MIN_TIME_PER_ACTION = 1.0

# --- Persona Definitions ---
# Structure: { 'persona_name': { param_category: { difficulty/setting: value } } }
PERSONA_PARAMS = {
    "topper": {
        "time_mean": {"Easy": 40, "Medium": 70, "Hard": 135},
        "time_std": {"Easy": 5, "Medium": 10, "Hard": 15},
        "accuracy": {"Easy": 0.97, "Medium": 0.90, "Hard": 0.80},
        "change_prob": 0.05,
        "jump_prob": 0.05,
        "tab_switch_prob": 0.005, # Very low overall chance per test
        "revisit_focus": "Hard" # More likely to revisit hard ones
    },
    "average": {
        "time_mean": {"Easy": 60, "Medium": 90, "Hard": 175},
        "time_std": {"Easy": 10, "Medium": 15, "Hard": 25},
        "accuracy": {"Easy": 0.85, "Medium": 0.67, "Hard": 0.50},
        "change_prob": 0.15,
        "jump_prob": 0.15,
        "tab_switch_prob": 0.01,
        "revisit_focus": "Medium" 
    },
    "slow_careful": {
        "time_mean": {"Easy": 70, "Medium": 120, "Hard": 225},
        "time_std": {"Easy": 15, "Medium": 20, "Hard": 25},
        "accuracy": {"Easy": 0.90, "Medium": 0.77, "Hard": 0.60},
        "change_prob": 0.25,
        "jump_prob": 0.05,
        "tab_switch_prob": 0.01,
        "revisit_focus": "All" # Likely to revisit any
    },
    "overconfident": {
        "time_mean": {"Easy": 35, "Medium": 60, "Hard": 100},
        "time_std": {"Easy": 10, "Medium": 15, "Hard": 20},
        "accuracy": {"Easy": 0.70, "Medium": 0.50, "Hard": 0.30},
        "change_prob": 0.03,
        "jump_prob": 0.05,
        "tab_switch_prob": 0.005,
        "revisit_focus": "None" # Less likely to revisit
    },
    "struggler": {
        "time_mean": {"Easy": 40, "Medium": 85, "Hard": 190},
        "time_std": {"Easy": 20, "Medium": 35, "Hard": 110}, # High variation
        "accuracy": {"Easy": 0.60, "Medium": 0.40, "Hard": 0.20},
        "change_prob": 0.40, # High chance of changing
        "jump_prob": 0.25, # Skips around more
        "tab_switch_prob": 0.03, # Might search more often
        "revisit_focus": "All",
        "completion_factor": 0.8 # Might only attempt 80% of questions on average
    }
}

# --- Persona Distribution --- (Must sum to 1.0)
PERSONA_WEIGHTS = {
    "topper": 0.10,
    "average": 0.35,
    "slow_careful": 0.15,
    "overconfident": 0.15,
    "struggler": 0.25
}

# --- Helper Functions ---
def get_random_time(mean, std_dev, min_time=MIN_TIME_PER_ACTION):
    time_val = random.normalvariate(mean, std_dev)
    return max(min_time, time_val)

def get_timestamp(current_time_s):
    start_datetime = datetime.datetime(2024, 1, 1, 10, 0, 0, tzinfo=datetime.timezone.utc)
    current_datetime = start_datetime + datetime.timedelta(seconds=current_time_s)
    return current_datetime.isoformat(timespec='milliseconds').replace('+00:00', 'Z')

def select_answer(question, persona_params):
    """Simulates answer selection based on persona accuracy for the question difficulty."""
    difficulty = question["difficulty"]
    correct_prob = persona_params["accuracy"][difficulty]
    
    if random.random() < correct_prob:
        return question["correct_answer"]
    else:
        num_options = len(question["options"])
        wrong_options = [i for i in range(num_options) if i != question["correct_answer"]]
        return random.choice(wrong_options) if wrong_options else question["correct_answer"]

# --- Main Simulation Function for Detailed Normal ---
def generate_detailed_normal_log(persona_params, questions, time_limit):
    """Generates logs based on specific persona parameters."""
    logs = []
    current_time_s = 0.0
    current_question_idx = 0 
    selected_options = [None] * len(questions)
    visited_mask = [False] * len(questions)
    questions_to_attempt = len(questions)
    last_real_interaction_idx = 0 

    # Adjust number of questions for struggler persona
    if "completion_factor" in persona_params:
         questions_to_attempt = int(len(questions) * random.uniform(persona_params["completion_factor"] - 0.1, persona_params["completion_factor"] + 0.05))
         questions_to_attempt = max(1, min(len(questions), questions_to_attempt)) # Ensure bounds

    questions_attempted_count = 0

    # Start Test Log
    first_question_id = questions[0]["id"]
    current_time_s += get_random_time(2, 1) 
    logs.append({"location": first_question_id, "timestamp": get_timestamp(current_time_s), "activity_text": "Test Started"})
    nav_time = get_random_time(1.5, 0.5)
    current_time_s += nav_time
    logs.append({"location": questions[current_question_idx]["id"], "timestamp": get_timestamp(current_time_s), "activity_text": f"Selected question {current_question_idx}"})

    # Overall test tab switch chance
    test_tab_switch = random.random() < persona_params["tab_switch_prob"]
    tab_switch_time = get_random_time(15, 5) if test_tab_switch else 0
    tab_switch_inserted = False

    while current_time_s < time_limit and questions_attempted_count < questions_to_attempt:
        if not visited_mask[current_question_idx]: 
            question = questions[current_question_idx]
            difficulty = question["difficulty"]
            last_real_interaction_idx = current_question_idx

            # --- Thinking/Answering Time ---
            think_time_mean = persona_params["time_mean"][difficulty]
            think_time_std = persona_params["time_std"][difficulty]
            think_time = get_random_time(think_time_mean, think_time_std)
            current_time_s += think_time
            if current_time_s >= time_limit: break

            # --- Select Answer ---
            selected_option_idx = select_answer(question, persona_params)
            selected_options[current_question_idx] = selected_option_idx
            
            click_time = get_random_time(1.5, 0.5)
            current_time_s += click_time
            if current_time_s >= time_limit: break
            logs.append({"location": question["id"], "timestamp": get_timestamp(current_time_s), "activity_text": f"Selected option {selected_option_idx} for question {current_question_idx}"})

            # --- Answer Change ---
            if random.random() < persona_params["change_prob"]:
                change_delay = get_random_time(10, 5)
                current_time_s += change_delay
                if current_time_s >= time_limit: break
                logs.append({"location": question["id"], "timestamp": get_timestamp(current_time_s), "activity_text": f"Cleared option for question {current_question_idx}"})
                selected_options[current_question_idx] = None 
                new_selection_delay = get_random_time(5, 2)
                current_time_s += new_selection_delay
                if current_time_s >= time_limit: break                    
                new_selected_option_idx = select_answer(question, persona_params) 
                selected_options[current_question_idx] = new_selected_option_idx
                logs.append({"location": question["id"], "timestamp": get_timestamp(current_time_s), "activity_text": f"Selected option {new_selected_option_idx} for question {current_question_idx}"})                
            
            visited_mask[current_question_idx] = True
            questions_attempted_count += 1

        # --- Decide Next Question (Navigation) ---
        if questions_attempted_count >= questions_to_attempt: break 

        # Determine if revisiting based on focus
        revisit_prob = 0.0
        focus = persona_params.get("revisit_focus", "None")
        q_difficulty = questions[current_question_idx]["difficulty"]
        if focus == "All" or focus == q_difficulty:
             revisit_prob = persona_params.get("jump_prob", 0.1) * 0.5 # Higher chance to revisit if focus matches

        # Decide Jump vs Sequential vs Revisit
        action_rand = random.random()
        next_question_idx = -1

        if action_rand < revisit_prob: # Try revisit first if applicable
            visited_indices = [i for i, visited in enumerate(visited_mask) if visited and i != current_question_idx]
            if visited_indices:
                next_question_idx = random.choice(visited_indices)
        
        if next_question_idx == -1: # If not revisiting, decide jump or sequential
             jump = random.random() < persona_params["jump_prob"]
             if jump:
                 unvisited_indices = [i for i, visited in enumerate(visited_mask) if not visited]
                 if unvisited_indices: next_question_idx = random.choice(unvisited_indices)
                 else: jump = False # Can't jump if all visited
             
             if not jump or next_question_idx == -1: # Move sequentially
                 temp_idx = (current_question_idx + 1) % len(questions)
                 checked_count = 0
                 while visited_mask[temp_idx] and checked_count < len(questions):
                     temp_idx = (temp_idx + 1) % len(questions)
                     checked_count += 1                
                 if not visited_mask[temp_idx]: next_question_idx = temp_idx

        # Navigate if a valid next question is found
        if next_question_idx != -1 and next_question_idx != current_question_idx:
             current_question_idx = next_question_idx
             nav_time = get_random_time(1.5, 0.5)
             current_time_s += nav_time
             if current_time_s >= time_limit: break                 
             logs.append({"location": questions[current_question_idx]["id"], "timestamp": get_timestamp(current_time_s), "activity_text": f"Selected question {current_question_idx}"})
        elif questions_attempted_count >= questions_to_attempt: 
            break # All attempted questions done

        # --- Insert rare overall tab switch ---
        if test_tab_switch and not tab_switch_inserted and questions_attempted_count > questions_to_attempt / 2 : 
             switch_start_time = current_time_s
             current_time_s += tab_switch_time 
             if current_time_s >= time_limit: break                 
             logs.append({"location": None, "timestamp": get_timestamp(switch_start_time), "activity_text": "Tab Switched"})
             logs.append({"location": None, "timestamp": get_timestamp(current_time_s), "activity_text": "Returned to Test Tab"})
             tab_switch_inserted = True 

    # Final Submit Log
    final_q_id = questions[last_real_interaction_idx]["id"]
    if current_time_s < time_limit:
        submit_delay = get_random_time(1.5, 0.5)
        current_time_s += submit_delay
        current_time_s = min(current_time_s, time_limit - 0.001) 
        logs.append({"location": final_q_id, "timestamp": get_timestamp(current_time_s), "activity_text": "Submitted Test"})

    return logs, BASE_LABEL # Use the base label

# --- Main Loop ---
if __name__ == "__main__":
    start_time = time.time()

    # Create output directory if it doesn't exist
    if not os.path.exists(OUTPUT_DIR):
        print(f"Creating output directory: {OUTPUT_DIR}")
        os.makedirs(OUTPUT_DIR)
    else:
        print(f"Output directory already exists: {OUTPUT_DIR}")

    # Get persona names and weights for weighted random choice
    personas = list(PERSONA_WEIGHTS.keys())
    weights = list(PERSONA_WEIGHTS.values())

    print(f"\nGenerating {NUM_LOGS_TO_GENERATE} detailed normal logs across {len(personas)} personas...")
    
    try:
        from tqdm import tqdm
        iterator = tqdm(range(NUM_LOGS_TO_GENERATE))
    except ImportError:
        iterator = range(NUM_LOGS_TO_GENERATE)
        print("(Install 'tqdm' for progress bar)")

    generated_count = 0
    for i in iterator:
        # Choose a persona based on weights
        chosen_persona_name = random.choices(personas, weights=weights, k=1)[0]
        persona_params = PERSONA_PARAMS[chosen_persona_name]
        
        # Generate logs for this persona
        logs, label = generate_detailed_normal_log(persona_params, questions_data, TIME_LIMIT_SECONDS)
        
        output_data = {"label": label, "logs": logs}
        
        # Save the log file
        filename = os.path.join(OUTPUT_DIR, f"{BASE_LABEL}_{chosen_persona_name}_{i+1:04d}.json") # Include persona in filename for reference
        try:
            with open(filename, 'w') as f:
                json.dump(output_data, f) # No indent for smaller file size
            generated_count += 1
        except IOError as e:
            print(f"\nError saving file {filename}: {e}")

    end_time = time.time()
    total_time = end_time - start_time
    print(f"\nFinished generating detailed normal logs.")
    print(f"Successfully created: {generated_count} files")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Total time taken: {total_time:.2f} seconds") 